-- Migration: Add agent_notifications table for autonomous agent notifications
-- This table stores notifications generated by autonomous agents (morning briefing, evening review, etc.)
-- Different from push notifications which are device-specific

CREATE TABLE IF NOT EXISTS agent_notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Notification content
    title VARCHAR(200) NOT NULL,
    body TEXT NOT NULL,

    -- Notification metadata
    type VARCHAR(50) NOT NULL,  -- morning_briefing, evening_review, weekly_summary, smart_suggestions, etc.
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',  -- low, normal, high, urgent
    action_url TEXT,  -- Optional deep link or action URL

    -- Tracking
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at TIMESTAMPTZ,  -- When user viewed the notification
    dismissed_at TIMESTAMPTZ,  -- When user dismissed the notification

    -- Constraints
    CONSTRAINT fk_agent_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_priority CHECK (priority IN ('low', 'normal', 'high', 'urgent'))
);

-- Indexes for efficient querying
CREATE INDEX idx_agent_notifications_user_id ON agent_notifications(user_id);
CREATE INDEX idx_agent_notifications_created_at ON agent_notifications(created_at DESC);
CREATE INDEX idx_agent_notifications_unread ON agent_notifications(user_id, read_at) WHERE read_at IS NULL;
CREATE INDEX idx_agent_notifications_type ON agent_notifications(user_id, type);

-- Add comment
COMMENT ON TABLE agent_notifications IS 'Agent-generated notifications (briefings, summaries, insights) stored for user retrieval';
